namespace FastScript.Grammar;

public class TokenList
{

    public enum Tokens : int
    {
        LPAR = 1,
        RPAR = 2,
        LSQB = 3,
        RSQB  = 4,
        COLON = 5,
        COMMA = 6,
        SEMI = 7,
        PLUS = 8,
        MINUS = 9,
        STAR = 10,
        SLASH = 11,
        VBAR = 12,
        AMPER = 13,
        LESS = 14,
        GREATER = 15,
        EQUAL = 16,
        DOT= 17,
        PERCENT = 18,
        LBRACE = 19,
        RBRACE = 20,
        EQEQUAL = 21,
        NOTEQUAL = 22,
        LESSEQUAL = 23,
        GREATEREQUAL = 24,
        TILDE = 25,
        CIRCUMFLEX = 26,
        LEFTSHIFT = 27,
        RIGHTSHIFT = 28,
        DOUBLESTAR = 29,
        PLUSEQUAL = 30,
        MINEQUAL = 31,
        STAREQUAL = 32,
        SLASHEQUAL = 33,
        PERCENTEQUAL = 34,
        AMPEREQUAL = 35,
        VBAREQUAL = 36,
        CIRCUMFLEXEQUAL = 37,
        LEFTSHIFTEQUAL = 38,
        RIGHTSHIFTEQUAL = 39,
        DOUBLESTAREQUAL = 40,
        DOUBLESLASH = 41,
        DOUBLESLASHEQUAL = 42,
        AT = 43,
        ATEQUAL = 44,
        RARROW = 45,
        ELLIPSIS = 46,
        COLONEQUAL = 47,
        EXCLAMATION = 48,
    }

    public static readonly Dictionary<int, string> TokenMap = new Dictionary<int, string>()
    {
        { 1 , "(" },
        { 2 , ")" },
        { 3 , "[" },
        { 4 , "]" },
        { 5 , ":" },
        { 6 , "," },
        { 7 , ";" },
        { 8 , "+" },
        { 9 , "-" },
        { 10 , "*" },
        { 11 , "/" },
        { 12 , "|" },
        { 13 , "&" },
        { 14 , "<" },
        { 15 , ">" },
        { 16 , "=" },
        { 17 , "." },
        { 18 , "%" },
        { 19 , "{" },
        { 20 , "}" },
        { 21 , "==" },
        { 22 , "!=" },
        { 23 , "<=" },
        { 24 , ">=" },
        { 25 , "~" },
        { 26 , "^" },
        { 27 , "<<" },
        { 28 , ">>" },
        { 29 , "**" },
        { 30 , "+=" },
        { 31 , "-=" },
        { 32 , "*=" },
        { 33 , "/=" },
        { 34 , "%=" },
        { 35 , "&=" },
        { 36 , "|=" },
        { 37 , "^=" },
        { 38 , "<<=" },
        { 39 , ">>=" },
        { 40 , "**=" },
        { 41 , "//" },
        { 42 , "//=" },
        { 43 , "@" },
        { 44 , "@=" },
        { 45 , "->" },
        { 46 , "..." },
        { 47 , ":=" },
        { 48 , "!" }
    };

}